[package]
name = "spider_firewall"
version = "2.28.6"
authors = [
    "j-mendez <jeff@spider.cloud>"
]
description = "Firewall to use for Spider Web Crawler."
repository = "https://github.com/spider-rs/spider_firewall"
readme = "README.md"
keywords = ["crawler", "firewall"]
categories = ["web-programming", "command-line-utilities"]
license = "MIT"
documentation = "https://docs.rs/spider_firewall"
edition = "2018"

[dependencies]
phf = "0.11"

[build-dependencies]
phf = "0.11"
phf_codegen = "0.11"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hashbrown = "0.15"